# Generated by Django 3.2 on 2024-01-25 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Score must be in range 1 - 10.'), django.core.validators.MinValueValidator(1, 'Score must be in range 1 - 10.')]),
        ),
    ]
