# Generated by Django 3.2 on 2024-01-29 15:36

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.check_username], verbose_name='Логин'),
        ),
    ]
