# Generated by Django 3.2 on 2024-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'User'), ('Модератор', 'Moderator'), ('Администратор', 'Admin')], default='Пользователь', max_length=30, verbose_name='Роль'),
        ),
    ]
