# Generated by Django 3.2 on 2024-01-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_apiuser_username'),
        ('reviews', '0002_alter_title_year'),
    ]

    operations = [
    ]
