# Generated by Django 3.2 on 2024-01-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment'),
        ('reviews', '0007_customuser_bio'),
    ]

    operations = [
    ]
